env_name: "highway-v0"

reward_weights:
  collision_penalty: -2.0
  high_speed_reward: 1.0
  right_lane_reward: 0.3
  on_road_reward: 1.0

train:
  total_timesteps: 50000
  learning_rate: 0.0003
  n_steps: 1024
  batch_size: 64
  gamma: 0.99